spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HospitalManagementSystem?createDatabaseIfNotExist=true
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true